import { getAction, Job, Workflow } from "../generated/index.js";

const checkout = getAction("actions/checkout@v4");
const downloadArtifact = getAction("actions/download-artifact@v4");
const githubScript = getAction("actions/github-script@v7");
const setupNode = getAction("actions/setup-node@v4");
const uploadArtifact = getAction("actions/upload-artifact@v4");
const setupDeno = getAction("denoland/setup-deno@v2");

const main = new Job("ubuntu-latest")
    .steps(s => s
        .add(githubScript({
            id: "get-commit",
            name: "Get commit hash from runtime_artifact_workflow_run_id",
            with: {
                "github-token": "${{ github.token }}",
                script: `const runId = '\${{ inputs.runtime_artifact_workflow_run_id }}';
const targetRepo = '\${{ github.repository }}-runtime';
const [owner, repo] = targetRepo.split('/');
const { data: run } = await github.rest.actions.getWorkflowRun({
  owner,
  repo,
  run_id: runId
});
const commitHash = run.head_sha;
if (!commitHash || !/^[0-9a-fA-F]{40}$/.test(commitHash)) {
  core.setFailed('Commit hash is missing or not a valid SHA-1: ' + commitHash);
  throw new Error('Commit hash is missing or not a valid SHA-1: ' + commitHash);
}
core.setOutput('commit_hash', commitHash);
`,
            },
            "if": "${{ inputs.runtime_artifact_workflow_run_id != '' }}",
        }))
        .add(checkout({
            name: "Checkout ${{ github.repository }}-runtime",
            with: {
                repository: "${{ github.repository }}-runtime",
                ref: "${{ steps.get-commit.outputs.commit_hash }}",
                submodules: "recursive",
                "fetch-depth": 1,
                filter: "blob:none",
            },
        }))
        .add({
            name: "Apply upstream patches",
            run: `# overlay(上流を丸ごと差し替えるファイル。焼くときの bsys6 build.sh と同じ)。
# artifacts.py の product = "noraneko" がここに居る。無いと mach artifact が zip の中の noraneko/ を見つけられない
OVERLAY_DIR=".github/overlays"
if [ -d "$OVERLAY_DIR" ]; then
  (cd "$OVERLAY_DIR" && find . -type f ! -name 'UPSTREAM_BASE' | while read -r f; do
    mkdir -p "$GITHUB_WORKSPACE/$(dirname "$f")"
    cp "$f" "$GITHUB_WORKSPACE/$f"
    echo "overlay: $f"
  done)
fi
PATCH_DIR=".github/patches/upstream"
if [ -d "$PATCH_DIR" ]; then
  for patch in "$PATCH_DIR"/*.patch; do
    [ -e "$patch" ] || continue
    echo "Applying patch: $(basename "$patch")"
    git apply --verbose "$patch"
  done
else
  echo "Patch directory not found, skipping patch application."
fi
`,
        })
        .add(checkout({
            name: "Checkout ${{ github.repository }}",
            with: {
                path: "noraneko",
            },
        }))
        .add(setupNode({
            with: {
                "node-version": 22,
            },
        }))
        .add(setupDeno({
            with: {
                "deno-version": "v2.x",
            },
        }))
        .add({
            name: "Setup Noraneko",
            run: `cd noraneko
deno install --allow-scripts
`,
        })
        .add({
            name: "Setup",
            run: `sudo apt install msitools -y
./mach --no-interactive bootstrap --application-choice browser_artifact_mode
`,
        })
        .add({
            name: "Write Versions",
            run: `cd noraneko
deno task feles-build misc writeVersion
`,
        })
        .add({
            name: "Mach configure",
            run: `#!/bin/bash
set -e
PLATFORM="\${{inputs.platform}}"
case "$PLATFORM" in
  "Windows-x86_64") cp ./.github/workflows/mozconfigs/windows-x86_64.mozconfig mozconfig ;;
  "Linux-x86_64") cp ./.github/workflows/mozconfigs/linux-x86_64.mozconfig mozconfig ;;
  "macOS-aarch64") cp ./.github/workflows/mozconfigs/macos-aarch64.mozconfig mozconfig ;;
esac
cp -r ./.github/assets/branding/* ./browser/branding/
mkdir -p noraneko/static/gecko/config/autogenerated
echo "$(cat noraneko/static/gecko/config/version.txt)@$(cat browser/config/version.txt)" > noraneko/static/gecko/config/autogenerated/version.txt
echo "$(cat noraneko/static/gecko/config/version_display.txt)@$(cat browser/config/version_display.txt)" > noraneko/static/gecko/config/autogenerated/version_display.txt
cat >> mozconfig << EOF
ac_add_options --with-version-file-path=noraneko/static/gecko/config/autogenerated
ac_add_options --enable-release
ac_add_options --enable-update-channel=alpha
ac_add_options --disable-tests
ac_add_options --enable-artifact-builds
mk_add_options MOZ_OBJDIR=./obj-artifact-build-output
ac_add_options --disable-updater
EOF
sed -i 's|ac_add_options --enable-unverified-updates||g; s|ac_add_options --enable-chrome-format=flat||g; s|ac_add_options --enable-optimize[^ ]*||g; s|^export CC=.*||g; s|^export CXX=.*||g; s|ac_add_options --enable-linker[^ ]*||g; s|ac_add_options --enable-lto[^ ]*||g' ./mozconfig
sed -i 's|MOZ_BRANDING_DIRECTORY=browser/branding/unofficial|MOZ_BRANDING_DIRECTORY=browser/branding/noraneko-unofficial|g' ./browser/confvars.sh
if [ "$PLATFORM" = "macOS-aarch64" ]; then
  sudo apt install -y zstd
  mkdir -p ~/tools
  curl -L "https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/gecko.cache.level-3.toolchains.v3.linux64-libdmg.latest/artifacts/public/build/dmg.tar.zst" -o dmg.tar.zst
  curl -L "https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/gecko.cache.level-3.toolchains.v3.linux64-hfsplus.latest/artifacts/public/build/hfsplus.tar.zst" -o hfsplus.tar.zst
  tar --zstd -xf dmg.tar.zst -C ~/tools
  tar --zstd -xf hfsplus.tar.zst -C ~/tools
  chmod 755 ~/tools/dmg/dmg ~/tools/dmg/hfsplus ~/tools/hfsplus/newfs_hfs
  cat >> mozconfig << EOF
DMG_TOOL=$HOME/tools/dmg/dmg
HFS_TOOL=$HOME/tools/dmg/hfsplus
MKFSHFS=$HOME/tools/hfsplus/newfs_hfs
EOF
fi
./mach configure
# -C1: パッチの文脈は上流の版で動く(155 で moz.build の DIRS の後ろが変わった)。要るのは近くの一行だけ
git apply -C1 --ignore-space-change --ignore-whitespace .github/patches/packaging/*.patch
`,
        })
        .add({
            name: "Possibly retrieve run ID if not provided",
            run: `if [ -z "\${{ inputs.runtime_artifact_workflow_run_id }}" ]; then
  echo "RUNTIME_ARTIFACT_WORKFLOW_RUN_ID=false" >> $GITHUB_ENV
else
  echo "RUNTIME_ARTIFACT_WORKFLOW_RUN_ID=\${{ inputs.runtime_artifact_workflow_run_id }}" >> $GITHUB_ENV
fi
`,
        })
        .add({
            name: "Get Artifact Name",
            run: `#!/bin/bash
set -e
case "$BUILD_PLATFORM" in
  "Windows-x86_64")
    echo "ARTIFACT_NAME=noraneko-windows-x86_64-moz-artifact" >> $GITHUB_ENV
    echo "ARTIFACT_FROM_RELEASE_NAME=noraneko-windows-x86_64-moz-artifact.zip" >> $GITHUB_ENV
    echo "OUTPUT_NAME=windows-x86_64" >> $GITHUB_ENV
    # makensis.mk の installer:: は mach repackage installer に -o $(DIST)/$(PKG_PATH)$(PKG_INST_BASENAME).exe を渡す。
    # PKG_PATH は空なので、installer は dist/ の直下に出る(install/sea/ ではない)
    echo "INSTALLER_PATH=noraneko*.installer.exe" >> $GITHUB_ENV
    echo "OUTPUT_INSTALLER_NAME=noraneko-windows-x86_64-installer.exe" >> $GITHUB_ENV
    ;;
  "Linux-x86_64")
    echo "ARTIFACT_NAME=noraneko-linux-x86_64-moz-artifact" >> $GITHUB_ENV
    echo "ARTIFACT_FROM_RELEASE_NAME=noraneko-linux-x86_64-moz-artifact.tar.xz" >> $GITHUB_ENV
    echo "OUTPUT_NAME=linux-x86_64" >> $GITHUB_ENV
    echo "INSTALLER_PATH=noraneko*tar.xz" >> $GITHUB_ENV
    echo "OUTPUT_INSTALLER_NAME=noraneko-linux-x86_64.tar.xz" >> $GITHUB_ENV
    ;;
  "macOS-aarch64")
    echo "ARTIFACT_NAME=noraneko-macos-aarch64-moz-artifact" >> $GITHUB_ENV
    echo "ARTIFACT_FROM_RELEASE_NAME=noraneko-macos-aarch64-moz-artifact.tar.gz" >> $GITHUB_ENV
    echo "OUTPUT_NAME=macos-aarch64" >> $GITHUB_ENV
    echo "INSTALLER_PATH=noraneko*.dmg" >> $GITHUB_ENV
    echo "OUTPUT_INSTALLER_NAME=noraneko-macos-aarch64.dmg" >> $GITHUB_ENV
    ;;
  *)
    echo "Unknown platform: $BUILD_PLATFORM"
    exit 1
    ;;
esac
echo "Environment variables set for platform: $BUILD_PLATFORM"
`,
            shell: "bash",
            env: {
                FORCE_COLOR: 3,
                BUILD_PLATFORM: "${{ inputs.platform }}",
            },
        })
        .add(downloadArtifact({
            name: "Download mozilla artifact from Actions",
            with: {
                name: "${{ env.ARTIFACT_NAME }}",
                "run-id": "${{ env.RUNTIME_ARTIFACT_WORKFLOW_RUN_ID }}",
                "github-token": "${{ github.token }}",
                repository: "${{ github.repository }}-runtime",
                path: "~/downloads",
            },
            "if": "${{ env.RUNTIME_ARTIFACT_WORKFLOW_RUN_ID != 'false' }}",
        }))
        .add({
            name: "Download Mozilla Artifact (dl.f3liz.casa, then GitHub Releases)",
            run: `mkdir -p ~/downloads
# 箱(noraneko-ci)が焼いた runtime を dl.f3liz.casa から。GitHub の release は 2025-09(143)で止まっている。
# /latest/<target> は /noraneko-runtime/<sha10>/<file> へ 302 するので、行き先の名前をそのまま使う。
# dl に無い組(Linux-x86_64)と、形が違う組(macOS は dl が tar.xz、こちらは dmg を待っている)は release に落ちる。
FINAL=""
if [ "\${{inputs.platform}}" != "macOS-aarch64" ]; then
  FINAL=$(curl -sfLI -o /dev/null -w '%{url_effective}' "https://dl.f3liz.casa/noraneko-runtime/latest/$OUTPUT_NAME") || FINAL=""
fi

if [ -n "$FINAL" ]; then
  echo "runtime from dl: $FINAL"
  curl -fL "$FINAL" -o ~/downloads/"$(basename "$FINAL")"
  # xpt_artifacts.zip(artifact build の mach package が要る)。産物と同じ名前で拡張子だけ違う
  stem=$(basename "$FINAL"); stem=\${stem%.zip}; stem=\${stem%.tar.xz}
  curl -fL "$(dirname "$FINAL")/$stem.xpt_artifacts.zip" -o ~/downloads/"$stem.xpt_artifacts.zip" \\
    || echo "no $stem.xpt_artifacts.zip next to it"
else
  echo "dl has nothing for $OUTPUT_NAME; falling back to GitHub Releases"
  curl -fL https://github.com/\${{ github.repository }}-runtime/releases/latest/download/\${{ env.ARTIFACT_FROM_RELEASE_NAME }} -o ~/downloads/\${{ env.ARTIFACT_FROM_RELEASE_NAME }}
fi
`,
            "if": "${{ env.RUNTIME_ARTIFACT_WORKFLOW_RUN_ID == 'false' }}",
        })
        .add({
            name: "Prepare Mozilla Artifact",
            run: `mkdir -p ~/artifacts
cp -r ~/downloads/* ~/artifacts
echo "=== Artifact contents ==="
ls -R ~/artifacts
# Validate artifact exists
# xpt_artifacts.zip も noraneko-*.zip なので、そちらを掴まないように外す
case "\${{inputs.platform}}" in
  "Windows-x86_64") PAT="noraneko-*.zip" ;;
  "Linux-x86_64") PAT="noraneko-*.tar.xz" ;;
  "macOS-aarch64") PAT="noraneko-*.dmg" ;;
esac
FOUND=$(find ~/artifacts -name "$PAT" ! -name "*.xpt_artifacts.zip" -type f | head -n 1)
if [ -z "$FOUND" ]; then
  echo "::error::No Mozilla artifact found in ~/artifacts for platform \${{inputs.platform}}"
  exit 1
fi
echo "Found artifact: $FOUND"
`,
        })
        .add({
            name: "Build Noraneko",
            run: `cd noraneko
NODE_ENV='production' deno task feles-build build --phase before-mach
`,
        })
        .add({
            name: "Build",
            run: `./mach configure
case "\${{inputs.platform}}" in
  "Windows-x86_64") PAT="noraneko-*.zip" ;;
  "Linux-x86_64") PAT="noraneko-*.tar.xz" ;;
  "macOS-aarch64") PAT="noraneko-*.dmg" ;;
esac
ART=$(find ~/artifacts -name "$PAT" ! -name "*.xpt_artifacts.zip" -type f | head -n 1)
# MOZ_ARTIFACT_FILE は : 区切りで複数。xpt_artifacts.zip があれば一緒に渡す(mach package が xpt を要る)
XPT=$(find ~/artifacts -name "*.xpt_artifacts.zip" -type f | head -n 1)
MOZ_ARTIFACT_FILE="$ART\${XPT:+:$XPT}" ./mach build
`,
        })
        .add({
            name: "Inject Noraneko",
            run: `cd noraneko
deno task feles-build build --phase after-mach
rsync -aL ../obj-artifact-build-output/dist/bin/ ../obj-artifact-build-output/dist/tmp__bin
rm -rf ../obj-artifact-build-output/dist/bin
mv ../obj-artifact-build-output/dist/tmp__bin ../obj-artifact-build-output/dist/bin
if [ "\${{inputs.platform}}" == "macOS-aarch64" ]; then
  for patch_file in ./tools/build/tasks/git-patches/patches/*.patch; do
    for resource_dir in ../obj-artifact-build-output/dist/*.app/Contents/Resources; do
      if patch --follow-symlinks --dry-run -d "$resource_dir" -p1 < "$patch_file"; then
        patch --follow-symlinks -d "$resource_dir" -p1 < "$patch_file"
      else
        echo "Dry-run failed for $patch_file in $resource_dir" >&2
        exit 1
      fi
    done
  done
fi
`,
        })
        .add({
            name: "Package noraneko",
            run: `./mach package
`,
        })
        .add({
            name: "mkdir noraneko-installer",
            run: `mkdir -p ~/noraneko-installer
sudo apt install -y build-essential debhelper
`,
        })
        .add({
            name: "Package noraneko deb",
            run: `./mach repackage deb --input "$(echo obj-*/dist/$INSTALLER_PATH)" --output ~/noraneko-installer/noraneko.deb --arch x86_64 --version "$(cat noraneko/static/gecko/config/version.txt || echo '0.3.0')" --build-number 1 --templates browser/installer/linux/app/debian --release-type release --product noraneko
`,
            "if": "${{ inputs.platform == 'Linux-x86_64' }}",
        })
        .add({
            name: "Rename and move installer",
            run: `mv obj-*/dist/$INSTALLER_PATH ~/noraneko-installer/$OUTPUT_INSTALLER_NAME
`,
        })
        .add(uploadArtifact({
            name: "Publish dist",
            with: {
                name: "noraneko-${{ env.OUTPUT_NAME }}-installer",
                path: "~/noraneko-installer/*",
                "compression-level": 9,
            },
        }))
    )
    .outputs({ run_id: "${{ github.run_id }}" });

const workflow = new Workflow({
    name: "(A) 📦️ Package",
    on: {
        workflow_dispatch: {
            inputs: {
                platform: {
                    type: "choice",
                    required: true,
                    default: "Windows-x86_64",
                    options: ["Windows-x86_64", "Linux-x86_64", "macOS-aarch64"],
                },
                runtime_artifact_workflow_run_id: {
                    type: "string",
                    default: "",
                    required: false,
                },
            },
        },
        workflow_call: {
            inputs: {
                platform: {
                    type: "string",
                    default: "Windows-x86_64",
                    required: true,
                },
                runtime_artifact_workflow_run_id: {
                    type: "string",
                    default: "",
                    required: false,
                },
            },
        },
    },
}).jobs(j => j
    .add("main", main)
);

// `run-name` is not expressible through the Workflow builder, so splice it into
// the serialized definition and re-emit via fromObject.
const def = workflow.toJSON();
(def as { "run-name"?: string })["run-name"] = "📦️ Package ${{ inputs.platform }}";
Workflow.fromObject(def).build("package");
