# SPDX-License-Identifier: MPL-2.0

name: "(A) 🚀 Release Alpha"

on:
  workflow_dispatch:
    inputs:
      runtime_windows_artifact_workflow_run_id:
        description: "The workflow run ID for the Windows runtime artifact (leave empty for latest release)"
        required: false
        type: string
      runtime_linux_artifact_workflow_run_id:
        description: "The workflow run ID for the Linux runtime artifact (leave empty for latest release)"
        required: false
        type: string

permissions:
  contents: write

run-name: "🚀 Release Alpha"

jobs:
  package-windows:
    uses: ./.github/workflows/package.yml
    with:
      platform: Windows-x86_64
      runtime_artifact_workflow_run_id: ${{ inputs.runtime_windows_artifact_workflow_run_id }}
    secrets: inherit

  package-linux:
    uses: ./.github/workflows/package.yml
    with:
      platform: Linux-x86_64
      runtime_artifact_workflow_run_id: ${{ inputs.runtime_linux_artifact_workflow_run_id }}
    secrets: inherit

  publish:
    needs: [package-windows, package-linux]
    uses: ./.github/workflows/publish_alpha.yml
    with:
      win_runtime_artifact_workflow_call: ${{ github.run_id }}
      linux_runtime_artifact_workflow_call: ${{ github.run_id }}
